sudo:
  false
language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
cache:
  pip
script:
  coverage run -m unittest discover tests
  #coverage run --source=pycool -m unittest tests
after_success:
  coveralls
